---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2022
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

name: Sync
# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  rebase-dev-es-branch:
    name: Rebase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12
      - name: Opening pull request
        id: pull
        uses: tretuna/sync-branches@1.4.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: "main"
          TO_BRANCH: "dev-es"
          PULL_REQUEST_TITLE: "chore: sync '{TO_BRANCH}' from {FROM_BRANCH} branch"
